### PR TITLE
fix!: Rework errors surfaced when encountering files or symlinks

### LINKED ISSUE #2: Errors with ENOENT when directory is a dangling link
I think we can either fix the error case or show a better error.  Ref https://github.com/cristianl/testcase-vinyl-bug

cc @erikkemperman

### PR DESCRIPTION
**Pull request by phated**
Ref #2

### CODE REVIEW

**Comment by phated** [comment]
@sttk @yocontra Can either of you review these changes for me? They are primarily just making the error messages more accurate and adding a test suite for symlinks.

File: mkdirp.js [hunk 1]
```diff
@@ -6,6 +6,24 @@ var fs = require('graceful-fs');
 
 var MASK_MODE = parseInt('7777', 8);
 
+// Utility for passing dirpath that was used with `fs.stat`
+function stat(dirpath, cb) {
```
Comment (sttk) [inline mkdirp.js:10]: Is this `stat` function necessary?
This code is seemed that `stat` is executed and if it causes an error, then `lstat` is executed.
I think that this code can work with only `lstat`.

File: mkdirp.js [hunk 2]
```diff
@@ -22,7 +40,7 @@ function mkdirp(dirpath, mode, callback) {
```
Comment (sttk) [inline mkdirp.js:40]: `fs.mkdir` is added an option `recursive` from nodejs v10.12.0.
Can this options be used to reduce repeated challenges of `fs.mkdir`?

**Review by sttk — COMMENTED** [review]
@phated I've reviewed this PR.

File: mkdirp.js (hunk 1 above)
Comment (phated) [reply mkdirp.js:10]: Yes, this is needed because `onStat` is used in many different contexts and we always want to pass the dirpath that was stat'ed

File: mkdirp.js (hunk 2 above)
Comment (phated) [reply mkdirp.js:40]: Node's recursive mkdir does not operate in the same way as the *nix `mkdir` utility. That is why we re-implemented  an alternative to the npm `mkdirp` package.

Comment (phated) [reply mkdirp.js:40]: For instance, node's mkdirp doesn't set the correct permissions on intermediate directories.

**Comment by sttk** [comment]
@phated I think this is good. Great work!

**Comment by phated** [comment]
Thanks for your review @sttk 🎉
